#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/27244fea-b26d-4669-bf2c-39cf3dffe884 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String cup_id;
  String message_log;
  CloudTime time_log;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
//#include "messages.h"
#include "vote_cups.h"
//thermal printer
#include <SoftwareSerial.h>
#include <Adafruit_Thermal.h>

#define TX_PIN 6
#define RX_PIN 5

SoftwareSerial mySerial(RX_PIN, TX_PIN);
Adafruit_Thermal printer(&mySerial);
int buzzer = 4;
//int message_count = 0;
//int previous_pointer = -1;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  //thermal printer setup
  mySerial.begin(19200);
  printer.begin();
  printer.sleep();
  
  
  pinMode(buzzer, OUTPUT);
  randomSeed(analogRead(0));
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
}



/*
  Since CupId is READ_WRITE variable, onCupIdChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onCupIdChange()  {

  digitalWrite(buzzer, HIGH);
  delay(500);
  digitalWrite(buzzer, LOW);
  
  //select message from file messages.h
  int countMessages = sizeof(messages) / sizeof(messages[0]);
  int randomizedPointer = 0;
 
  do {
        randomizedPointer = random(0, countMessages);
    } while (randomizedPointer == previous_pointer);

  previous_pointer = randomizedPointer;
  
  char *printerMessage = messages[randomizedPointer];
    
  //Serial.println(countMessages);
  //Serial.println(randomizedPointer);
  //Serial.println(messages[randomizedPointer]);
  //Serial.println(printerMessage);

  printer.wake();
  println(printerMessage);
  printer.feed(3);
  printer.sleep();

  message_count++;
  message_log = String(printerMessage + message_count);
  time_log = ArduinoCloud.getLocalTime();
}
