// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCupIdChange();

String cup_id;
String message_log;
CloudTime time_log;

void initProperties(){

  ArduinoCloud.addProperty(cup_id, READWRITE, ON_CHANGE, onCupIdChange);
  ArduinoCloud.addProperty(message_log, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(time_log, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
